//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.18 at 02:20:01 ���� CST 
//

/**
 * 安卓应用更新服务所需类
 */
@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://herald.seu.edu.cn/ws/android-update",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cn.edu.seu.herald.ws.api.update;
