//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.19 at 03:43:46 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://herald.seu.edu.cn/ws/grade-point", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cn.edu.seu.herald.ws.api.gpa;
